enabled: true

# HTTP代理地址
# 示例格式
# proxy: { "all://": "http://127.0.0.1:1081" }
proxy: {}

account:
  # 通过用户名和密码进行登录的选项已经被Pixiv官方弃用
  # 请参考 https://github.com/mixmoe/HibiAPI/issues/53 以获得更多信息
  token: "" # Pixiv 登录凭证刷新令牌 (Refresh Token)

language: zh-cn # 返回语言, 会影响标签的翻译
