enabled: true

# HTTP代理地址
# 示例格式
# proxy:
#   http_proxy: http://127.0.0.1:1081
#   https_proxy: https://127.0.0.1:1081
proxy: {}

account:
  # Login via username and password is deprecated due to external API changes
  # Please refer to https://github.com/mixmoe/HibiAPI/issues/53 to get more information
  token: "" # Pixiv 登录凭证刷新令牌 (Refresh Token)
  refresh-interval: 1800 # 刷新帐号登录凭证间隔,单位为秒

language: zh-cn # 返回语言, 会影响标签的翻译
